spring:
  application:
    name: spring-cloud-config-client
  cloud:
#    bus:
#     enabled: true
#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    username: guest
#    password: guest
management:
  endpoints:
    web:
      exposure:
        include: refresh
