spring:
  application:
    name: spring-cloud-config-client
  cloud:
    bus:
     enabled: true
  rabbitmq:
    host: 111.231.29.249
    port: 5672
    username: guest
    password: guest
management:
  endpoints:
    web:
      exposure:
        include: refresh
