spring:
  application:
    name: gateway-zuul
server:
  port: 8006
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/   #注册中心eurka地址
zuul:
  routes:
    config-client:
      path: /lxt/**
      serviceId:  spring-cloud-config-client
  retryable: true #是否开启重试功能
ribbon:
  MaxAutoRetries: 2 #对当前服务的重试次数
  MaxAutoRetriesNextServer: 0 #切换相同Server的次数