server:
  port: 8080
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hdlxt/springcloud # 配置git仓库的地址
          search-paths: config-repo                     # git仓库地址下的相对地址，可以配置多个，用,分割。
          username:                     # git仓库的账号
          password:           # git仓库的密码
  rabbitmq:
    host: 111.231.29.249
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/   #注册中心eurka地址
management:
  endpoints:
    web:
      exposure:
        # 2.x手动开启  这个是用来暴露 endpoints 的。由于 endpoints 中会包含很多敏感信息，除了 health 和 info 两个支持 web 访问外，其他的默认不支持 web 访问
        include: bus-refresh
