spring:
  application:
    name: spring-cloud-consul-consumer  #注册到consul的服务名称
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: consul-consumer #注册到consul的服务名称
        hostname: localhost #本机测试使用
server:
  port: 8014